# My configs for alert management
# The default route will receive alerts that do not match any other routes
route:
  receiver: 'default-receiver'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  group_by: ['alertname', 'job', 'instance', 'severity']

# Variables must be added to the file before execution
# Prometheus currently does not support referencing environment variables
receivers:
  - name: 'default-receiver'
    email_configs:
      - to: RECIPIENT_EMAIL
        from: SENDER_EMAIL
        smarthost: SMARTHOST
        auth_username: AUTH_USERNAME
        auth_password: AUTH_PASSWORD