version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring_network
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries
  
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - "9273:9273"
    networks:
      - monitoring_network

  node_exporter_1:
    image: prom/node-exporter
    container_name: node_exporter_1
    command: ["--web.listen-address=:9100"]
    ports:
      - "8080:9100"
    networks:
      - monitoring_network

  node_exporter_2:
    image: prom/node-exporter
    container_name: node_exporter_2
    command: ["--web.listen-address=:9100"]
    ports:
      - "8081:9100"
    networks:
      - monitoring_network

  node_exporter_3:
    image: prom/node-exporter
    container_name: node_exporter_3
    command: ["--web.listen-address=:9100"]
    ports:
      - "8082:9100"
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data: