# Define environment variables and settings for Grafana On-Call
version: "3.9"

x-environment: &oncall-environment
  DATABASE_TYPE: sqlite3
  BROKER_TYPE: redis
  BASE_URL: ${DOMAIN}
  SECRET_KEY: ${ONCALL_SECRET_KEY}
  FEATURE_PROMETHEUS_EXPORTER_ENABLED: "True"
  PROMETHEUS_EXPORTER_SECRET: ${PROMETHEUS_EXPORTER_SECRET:-}
  REDIS_URI: redis://redis:6379/0
  DJANGO_SETTINGS_MODULE: settings.hobby
  CELERY_WORKER_QUEUE: "default,critical,long,slack,telegram,webhook,retry,celery"
  CELERY_WORKER_CONCURRENCY: "1"
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "100"
  CELERY_WORKER_SHUTDOWN_INTERVAL: "65m"
  CELERY_WORKER_BEAT_ENABLED: "True"
  GRAFANA_API_URL: http://grafana:3000
  GRAFANA_CLOUD_ONCALL_API_URL: https://oncall-prod-eu-west-0.grafana.net/oncall

# Bridge is a default network driver that isolates containers within the same host
# Network is a general term for various types of network configurations used for container communication
networks:
  monitoring_network:
    driver: bridge

# Defines volumes to persist data for various services
volumes:
  grafana_data:
  prometheus_data:
  mssql_data:
  oncall_data:
  redis_data:
  prometheus_pyrra: {}

# Defines services that make up the monitoring stack
services:
  # Add configuration for Grafana service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-oncall-app
      GF_INSTALL_PLUGINS: grafana-oncall-app
    networks:
      - monitoring_network
    volumes:
      - grafana_data:/var/lib/grafana

  # Add configuration for Engine service
  engine:
    image: grafana/oncall
    container_name: engine
    restart: always
    ports:
      - "8080:8080"
    command: sh -c "uwsgi --ini uwsgi.ini"
    environment: *oncall-environment
    networks:
      - monitoring_network
    volumes:
      - oncall_data:/var/lib/oncall
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
    depends_on:
      redis:
        condition: service_healthy

  # Add configuration for Celery service
  celery:
    image: grafana/oncall
    container_name: celery
    restart: always
    command: sh -c "./celery_with_exporter.sh"
    environment: *oncall-environment
    networks:
      - monitoring_network
    volumes:
      - oncall_data:/var/lib/oncall
    depends_on:
      redis:
        condition: service_healthy

  # Add configuration for Redis service
  redis:
    image: redis:7.0.5
    container_name: redis
    restart: always
    expose:
      - 6379
    networks:
      - monitoring_network
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      interval: 5s
      retries: 10

  # Add configuration for NGINX service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - monitoring_network

  # Add configuration for Prometheus service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring_network
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./configs/prometheus.rules.yaml:/etc/prometheus/prometheus.rules.yaml
      - prometheus_data:/prometheus
      - ./prometheus_pyrra:/etc/prometheus/pyrra
    command: --config.file=/etc/prometheus/prometheus.yaml --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=33d --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries

  # Add configuration for Alertmanager service
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - monitoring_network
    volumes:
      - ./configs/alertmanager.yaml:/etc/alertmanager/alertmanager.yaml
    command: --config.file=/etc/alertmanager/alertmanager.yaml

  # Add configuration for Telegraf service
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./configs/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - "9273:9273"
    networks:
      - monitoring_network

  # Add configuration for Node Exporter #1 service
  node_exporter_1:
    image: prom/node-exporter
    container_name: node_exporter_1
    ports:
      - "8081:9100"
    networks:
      - monitoring_network
    volumes:
      - ./textfile-metrics:/textfile-metrics
      - ./custom-collectors/update-metrics.sh:/custom-collectors/update-metrics.sh
    command:
      [
        "--web.listen-address=:9100",
        "--collector.textfile.directory=textfile-metrics",
      ]

  # Add configuration for Node Exporter #2 service
  node_exporter_2:
    image: prom/node-exporter
    container_name: node_exporter_2
    ports:
      - "8082:9100"
    networks:
      - monitoring_network
    command: ["--web.listen-address=:9100"]

  # Add configuration for Node Exporter #3 service
  node_exporter_3:
    image: prom/node-exporter
    container_name: node_exporter_3
    ports:
      - "8083:9100"
    networks:
      - monitoring_network
    command: ["--web.listen-address=:9100"]

  # Add configuration for MSSQL service
  mssql_server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql_2019
    environment:
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: Y
      MSSQL_PID: Evaluation
    networks:
      - monitoring_network
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./sql-scripts:/scripts

  # Add configuration for SQL Exporter service
  sql_exporter:
    image: burningalchemist/sql_exporter
    container_name: sql_exporter
    ports:
      - "9399:9399"
    environment:
      DATABASENAME: ${DATABASENAME}
      MSSQL_SA_USER: ${SA_USER}
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
    volumes:
      - ./custom-collectors/sql-exporter/sql-exporter.yaml:/etc/custom-collectors/sql-exporter/sql-exporter.yaml
      - ./custom-collectors/sql-exporter/mssql-availability.collector.yaml:/etc/custom-collectors/sql-exporter/mssql-availability.collector.yaml
    networks:
      - monitoring_network
    command: --config.file=/etc/custom-collectors/sql-exporter/sql-exporter.yaml

  # Add configuration for MSSQL Exporter service
  mssql_exporter:
    image: awaragi/prometheus-mssql-exporter
    container_name: mssql_exporter
    ports:
      - "4000:4000"
    environment:
      USERNAME: ${SQL_USERNAME}
      PASSWORD: ${SQL_PASSWORD}
      SERVER: ${SQL_SERVER_NUMBER}

  # Add configuration for Pyrra service
  pyrra-api:
    image: ghcr.io/pyrra-dev/pyrra:v0.7.0
    container_name: pyrra
    restart: always
    networks:
      - monitoring_network
    ports:
      - "9099:9099"
    command:
      [
        "api",
        "--prometheus-url=http://prometheus:9090",
        "--prometheus-external-url=http://localhost:9090",
        "--api-url=http://pyrra-filesystem:9444",
      ]
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus_pyrra:/etc/prometheus/pyrra

  # Add configuration for Pyrra Filesystem service
  pyrra-filesystem:
    image: ghcr.io/pyrra-dev/pyrra:v0.7.0
    container_name: pyrra_files
    restart: always
    command:
      - filesystem
      - --prometheus-url=http://prometheus:9090
    networks:
      - monitoring_network
    volumes:
      - ./pyrra:/etc/pyrra
      - ./prometheus_pyrra:/etc/prometheus/pyrra
