version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring_network
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring_network
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./configs/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries
  
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - monitoring_network
    volumes:
      - ./configs/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command: --config.file=/etc/alertmanager/alertmanager.yml

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./configs/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - "9273:9273"
    networks:
      - monitoring_network

  node_exporter_1:
    image: prom/node-exporter
    container_name: node_exporter_1
    command: ["--web.listen-address=:9100"]
    ports:
      - "8080:9100"
    networks:
      - monitoring_network

  node_exporter_2:
    image: prom/node-exporter
    container_name: node_exporter_2
    command: ["--web.listen-address=:9100"]
    ports:
      - "8081:9100"
    networks:
      - monitoring_network

  node_exporter_3:
    image: prom/node-exporter
    container_name: node_exporter_3
    command: ["--web.listen-address=:9100"]
    ports:
      - "8082:9100"
    networks:
      - monitoring_network
  
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: sql_2019
    environment:
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: Y
      MSSQL_PID: Evaluation
    networks:
      - monitoring_network
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./sql-scripts:/scripts

  mssql_exporter:
    image: awaragi/prometheus-mssql-exporter
    container_name: mssql_exporter
    ports:
      - "4000:4000"
    environment:
      USERNAME: ${SQL_USERNAME}
      PASSWORD: ${SQL_PASSWORD}
      SERVER: ${SQL_SERVER_NUMBER}

networks:
  monitoring_network:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:
  mssql_data: