version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring_network

  node_exporter_8080:
    image: prom/node-exporter
    command: ["--web.listen-address=:9100"]
    ports:
      - "8080:9100"
    networks:
      - monitoring_network

  node_exporter_8081:
    image: prom/node-exporter
    command: ["--web.listen-address=:9100"]
    ports:
      - "8081:9100"
    networks:
      - monitoring_network

  node_exporter_8082:
    image: prom/node-exporter
    command: ["--web.listen-address=:9100"]
    ports:
      - "8082:9100"
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge