# Configuring and defining Prometheus rules
groups:
- name: cpu-node
  rules:
  # Record time series resulting from the expression
  - record: job_instance_mode:node_cpu_seconds:avg_rate5m
    expr: avg by (job, instance, mode) (rate(node_cpu_seconds_total[5m]))