# Configuring and defining Prometheus rules
groups:
  - name: cpu-node
    rules:
    # Record time series resulting from the expression
    - record: job_instance_mode:node_cpu_seconds:avg_rate5m
      expr: avg by (job, instance, mode) (rate(node_cpu_seconds_total[5m]))

  - name: cpu-telegraf
    rules:
    # Calculate the total CPU usage percentage based on telegraf metrics
    - record: total_cpu_usage_percentage
      expr: 100 - avg by (host) (cpu_usage_idle{cpu="cpu-total"})

    # Calculate the average CPU usage by CPU based on telegraf metrics
    - record: avg_cpu_usage_by_cpu
      expr: avg by (cpu) (100 - cpu_usage_idle)