# Configuration file for Prometheus Alertmanager

# The default route will receive alerts that do not match any other routes
route:
  receiver: 'default-receiver'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  group_by: ['alertname', 'job', 'instance', 'severity']

# Define route for custom alerts to use the custom-alerts-receiver
route:
  receiver: 'custom-alerts-receiver'
  match:
    alertname: 'custom_alert', 'high_windows_cpu_load', 'cpu-usage-alert', 'combined-cpu-usage-alert'

# Sender and receiver variables must be added to the file before execution
# Prometheus currently does not support referencing environment variables
receivers:
  - name: 'default-receiver'
    email_configs:
      - to: RECIPIENT_EMAIL
        from: SENDER_EMAIL
        smarthost: SMARTHOST
        auth_username: AUTH_USERNAME
        auth_password: AUTH_PASSWORD
    
  - name: 'custom-alerts-receiver'
    email_configs:
      - to: RECIPIENT_EMAIL
        from: SENDER_EMAIL
        smarthost: SMARTHOST
        auth_username: AUTH_USERNAME
        auth_password: AUTH_PASSWORD

# Inhibition rules allow for muting or grouping specific alerts, managing alert dependencies
# Here it is used to suppress warning alerts when a critical alert with the same alertname occurs
inhibit_rules:
  - source_match:
      severity: 'warning'
    target_match:
      severity: 'critical'
    equal: 'high_cpu_load_combined'