# Configuring and defining Prometheus rules

groups:
  - name: cpu-node
    rules:
    # Record time series resulting from expression based on Node Exporter labels
    - record: job_instance_mode:node_cpu_seconds:avg_rate5m
      expr: avg by (job, instance, mode) (rate(node_cpu_seconds_total[5m]))
    
  - name: cpu-windows-exporter
    rules:
    # Record percentage CPU usage for Windows Exporter
    - record: windows_cpu_usage_percentage
      expr: 100 - avg by (instance) (windows_cpu_idle)
  
    # Custom alert for when Windows CPU usage exceeds 90 percent
    - alert: high_windows_cpu_load
      expr: windows_cpu_usage_percentage > 90
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High Windows CPU Load Alert"
        description: "Windows CPU usage percentage has exceeded the threshold for 5 minutes."

  - name: cpu-telegraf
    rules:
    # Record total CPU usage percentage based on Telegraf metrics
    - record: telegraf_total_cpu_usage_percentage
      expr: 100 - avg by (host) (cpu_usage_idle{cpu="cpu-total"})

    # Record average CPU usage by CPU based on Telegraf metrics
    - record: avg_cpu_usage_by_cpu
      expr: avg by (cpu) (100 - cpu_usage_idle)
  
  - name: cpu-node-and-telegraf
    rules:
    # Record metrics from both Node Exporter and Telegraf on combined percentage CPU usage
    - record: combined_cpu_usage_percentage
      expr: avg_over_time(telegraf_total_cpu_usage_percentage[1h]) + avg_over_time(node_cpu_seconds_total[1h])

  - name: mssql-exporter
    rules:
    # Define metrics from MSSQL Exporter for later use in alert by creating recording rule
    - record: mssql_queries_executed_total
      expr: mssql_queries_executed_total

    # Alert when a large number of queries are executed in a short period
    - alert: high_query_rate
      expr: rate(mssql_queries_executed_total[5m]) > 100
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "High Query Rate Alert"
        description: "A high rate of SQL queries has been executed for 10 minutes."
  
  - name: cpu-usage-alert
    rules:
    # Custom alert for when Telegraf total percentage CPU usage exceeds threashold
    - alert: high_cpu_load
      expr: telegraf_total_cpu_usage_percentage > 50
      for: 10s
      labels:
        severity: warning
      annotations:
        summary: "High CPU Load Alert"
        description: "Total CPU usage percentage has exceeded the threshold for 10 seconds."

  - name: combined-cpu-usage-alert
    rules:
      # Custom alert for when the combined percentage CPU usage of Node Exporter and Telegraf exceeds threashold
      - alert: high_cpu_load
        expr: combined_cpu_usage_percentage > 80
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High Combined CPU Load Alert"
          description: "Total combined CPU usage percentage of Node Exporter and Telegraf has exceeded the threshold for 2 minutes."